# Generated by Django 2.2.10 on 2020-10-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201025_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='title',
            field=models.CharField(choices=[('CULTURE', 'Культура'), ('CITY', 'Город'), ('HEALTH', 'Здоровье'), ('SCIENCE', 'Наука'), ('INTERRELATION', 'Международные отношения')], max_length=1, verbose_name='Раздел статьи'),
        ),
    ]
