# Generated by Django 2.2.10 on 2020-10-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20201026_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescopes',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='title',
            field=models.CharField(choices=[('CULTURE', 'Культура'), ('CITY', 'Город'), ('HEALTH', 'Здоровье'), ('SCIENCE', 'Наука'), ('INTERRELATION', 'Международные отношения')], max_length=50, verbose_name='Раздел статьи'),
        ),
    ]
