# Generated by Django 3.1.2 on 2020-10-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20201026_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescopes',
            options={'verbose_name': 'Раздел и статья', 'verbose_name_plural': 'Разделы и статьи'},
        ),
        migrations.AlterField(
            model_name='scope',
            name='title',
            field=models.CharField(choices=[('CULTURE', 'Культура'), ('CITY', 'Город'), ('HEALTH', 'Здоровье'), ('SCIENCE', 'Наука'), ('INTERRELATION', 'Международные отношения'), ('SPACE', 'Космос')], max_length=50, verbose_name='Раздел статьи'),
        ),
    ]
