# Generated by Django 3.1.2 on 2020-10-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20201029_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='scope',
            name='scopes',
            field=models.ManyToManyField(through='articles.ArticleScopes', to='articles.Article'),
        ),
    ]
