# Generated by Django 3.1.2 on 2020-10-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20201029_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='scopes',
            new_name='mtm',
        ),
    ]
