# Generated by Django 3.1.2 on 2020-10-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20201029_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.ArticleScopes', to='articles.Scope'),
        ),
    ]
