# Generated by Django 3.1.2 on 2020-11-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_scopes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='mtm',
        ),
    ]
